resolver: lts-4.2

# Almost all warnings, plus minimal-imports for packunused
ghc-options:
  "*": -ddump-minimal-imports -Werror -Wall -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -fwarn-monomorphism-restriction -fwarn-auto-orphans -fwarn-missing-local-sigs -fwarn-missing-exported-sigs -fwarn-missing-import-lists -fwarn-identities

packages:
- '.'

# Programs used by CI to run additional tests
extra-deps:
- hlint-1.9.26
- packdeps-0.4.2.1
- cabal-install-1.22.7.0
